package StudySystem;


/**
* StudySystem/GossipMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class GossipMessage implements org.omg.CORBA.portable.IDLEntity
{
  public String messageId = null;
  public String type = null;
  public String payload = null;
  public long timestamp = (long)0;
  public long version = (long)0;
  public String sourceId = null;

  public GossipMessage ()
  {
  } // ctor

  public GossipMessage (String _messageId, String _type, String _payload, long _timestamp, long _version, String _sourceId)
  {
    messageId = _messageId;
    type = _type;
    payload = _payload;
    timestamp = _timestamp;
    version = _version;
    sourceId = _sourceId;
  } // ctor

} // class GossipMessage
