package StudySystem;

/**
* StudySystem/GossipMessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class GossipMessageHolder implements org.omg.CORBA.portable.Streamable
{
  public StudySystem.GossipMessage value = null;

  public GossipMessageHolder ()
  {
  }

  public GossipMessageHolder (StudySystem.GossipMessage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudySystem.GossipMessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudySystem.GossipMessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudySystem.GossipMessageHelper.type ();
  }

}
