package StudySystem;


/**
* StudySystem/PeerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/


// Interface principale du Peer
public abstract class PeerPOA extends org.omg.PortableServer.Servant
 implements StudySystem.PeerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getQuestions", new java.lang.Integer (0));
    _methods.put ("shareQuestion", new java.lang.Integer (1));
    _methods.put ("receiveGossip", new java.lang.Integer (2));
    _methods.put ("getPeerInfo", new java.lang.Integer (3));
    _methods.put ("registerPeer", new java.lang.Integer (4));
    _methods.put ("getKnownPeers", new java.lang.Integer (5));
    _methods.put ("getStatistics", new java.lang.Integer (6));
    _methods.put ("updateStatistics", new java.lang.Integer (7));
    _methods.put ("ping", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Gestion des questions
       case 0:  // StudySystem/Peer/getQuestions
       {
         String subject = in.read_string ();
         StudySystem.Question $result[] = null;
         $result = this.getQuestions (subject);
         out = $rh.createReply();
         StudySystem.QuestionSequenceHelper.write (out, $result);
         break;
       }


  // <-- USING TYPEDEF
       case 1:  // StudySystem/Peer/shareQuestion
       {
         StudySystem.Question q = StudySystem.QuestionHelper.read (in);
         this.shareQuestion (q);
         out = $rh.createReply();
         break;
       }


  // Protocole Gossip
       case 2:  // StudySystem/Peer/receiveGossip
       {
         StudySystem.GossipMessage msg = StudySystem.GossipMessageHelper.read (in);
         this.receiveGossip (msg);
         out = $rh.createReply();
         break;
       }


  // Gestion des peers
       case 3:  // StudySystem/Peer/getPeerInfo
       {
         StudySystem.PeerInfo $result = null;
         $result = this.getPeerInfo ();
         out = $rh.createReply();
         StudySystem.PeerInfoHelper.write (out, $result);
         break;
       }

       case 4:  // StudySystem/Peer/registerPeer
       {
         StudySystem.PeerInfo peerInfo = StudySystem.PeerInfoHelper.read (in);
         this.registerPeer (peerInfo);
         out = $rh.createReply();
         break;
       }

       case 5:  // StudySystem/Peer/getKnownPeers
       {
         StudySystem.PeerInfo $result[] = null;
         $result = this.getKnownPeers ();
         out = $rh.createReply();
         StudySystem.PeerInfoSequenceHelper.write (out, $result);
         break;
       }


  // Statistiques
       case 6:  // StudySystem/Peer/getStatistics
       {
         String studentId = in.read_string ();
         StudySystem.Statistics $result = null;
         $result = this.getStatistics (studentId);
         out = $rh.createReply();
         StudySystem.StatisticsHelper.write (out, $result);
         break;
       }

       case 7:  // StudySystem/Peer/updateStatistics
       {
         StudySystem.Statistics stats = StudySystem.StatisticsHelper.read (in);
         this.updateStatistics (stats);
         out = $rh.createReply();
         break;
       }


  // Utilitaires
       case 8:  // StudySystem/Peer/ping
       {
         boolean $result = false;
         $result = this.ping ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StudySystem/Peer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Peer _this() 
  {
    return PeerHelper.narrow(
    super._this_object());
  }

  public Peer _this(org.omg.CORBA.ORB orb) 
  {
    return PeerHelper.narrow(
    super._this_object(orb));
  }


} // class PeerPOA
