package StudySystem;


/**
* StudySystem/PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/


// Interface principale du Peer
public interface PeerOperations 
{

  // Gestion des questions
  StudySystem.Question[] getQuestions (String subject);

  // <-- USING TYPEDEF
  void shareQuestion (StudySystem.Question q);

  // Protocole Gossip
  void receiveGossip (StudySystem.GossipMessage msg);

  // Gestion des peers
  StudySystem.PeerInfo getPeerInfo ();
  void registerPeer (StudySystem.PeerInfo peerInfo);
  StudySystem.PeerInfo[] getKnownPeers ();

  // Statistiques
  StudySystem.Statistics getStatistics (String studentId);
  void updateStatistics (StudySystem.Statistics stats);

  // Utilitaires
  boolean ping ();
} // interface PeerOperations
