package StudySystem;

/**
* StudySystem/PeerInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class PeerInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public StudySystem.PeerInfo value = null;

  public PeerInfoHolder ()
  {
  }

  public PeerInfoHolder (StudySystem.PeerInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudySystem.PeerInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudySystem.PeerInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudySystem.PeerInfoHelper.type ();
  }

}
