package StudySystem;


/**
* StudySystem/PeerInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class PeerInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String peerId = null;
  public String host = null;
  public int port = (int)0;
  public long lastSeen = (long)0;

  public PeerInfo ()
  {
  } // ctor

  public PeerInfo (String _peerId, String _host, int _port, long _lastSeen)
  {
    peerId = _peerId;
    host = _host;
    port = _port;
    lastSeen = _lastSeen;
  } // ctor

} // class PeerInfo
