package StudySystem;

/**
* StudySystem/PeerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/


// Interface principale du Peer
public final class PeerHolder implements org.omg.CORBA.portable.Streamable
{
  public StudySystem.Peer value = null;

  public PeerHolder ()
  {
  }

  public PeerHolder (StudySystem.Peer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudySystem.PeerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudySystem.PeerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudySystem.PeerHelper.type ();
  }

}
