package StudySystem;

/**
* StudySystem/QuestionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class QuestionHolder implements org.omg.CORBA.portable.Streamable
{
  public StudySystem.Question value = null;

  public QuestionHolder ()
  {
  }

  public QuestionHolder (StudySystem.Question initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudySystem.QuestionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudySystem.QuestionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudySystem.QuestionHelper.type ();
  }

}
