package StudySystem;


/**
* StudySystem/QuestionSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/


// TYPEDEFS (Fix for previous error)
abstract public class QuestionSequenceHelper
{
  private static String  _id = "IDL:StudySystem/QuestionSequence:1.0";

  public static void insert (org.omg.CORBA.Any a, StudySystem.Question[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StudySystem.Question[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = StudySystem.QuestionHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (StudySystem.QuestionSequenceHelper.id (), "QuestionSequence", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StudySystem.Question[] read (org.omg.CORBA.portable.InputStream istream)
  {
    StudySystem.Question value[] = null;
    int _len0 = istream.read_long ();
    value = new StudySystem.Question[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = StudySystem.QuestionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StudySystem.Question[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      StudySystem.QuestionHelper.write (ostream, value[_i0]);
  }

}
