package StudySystem;


/**
* StudySystem/Question.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class Question implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String subject = null;
  public String content = null;
  public String answers[] = null;
  public String correctAnswer = null;
  public long timestamp = (long)0;
  public String authorId = null;

  public Question ()
  {
  } // ctor

  public Question (String _id, String _subject, String _content, String[] _answers, String _correctAnswer, long _timestamp, String _authorId)
  {
    id = _id;
    subject = _subject;
    content = _content;
    answers = _answers;
    correctAnswer = _correctAnswer;
    timestamp = _timestamp;
    authorId = _authorId;
  } // ctor

} // class Question
