package StudySystem;


/**
* StudySystem/QuestionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

abstract public class QuestionHelper
{
  private static String  _id = "IDL:StudySystem/Question:1.0";

  public static void insert (org.omg.CORBA.Any a, StudySystem.Question that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StudySystem.Question extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "subject",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "content",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "answers",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "correctAnswer",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[5] = new org.omg.CORBA.StructMember (
            "timestamp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "authorId",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (StudySystem.QuestionHelper.id (), "Question", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StudySystem.Question read (org.omg.CORBA.portable.InputStream istream)
  {
    StudySystem.Question value = new StudySystem.Question ();
    value.id = istream.read_string ();
    value.subject = istream.read_string ();
    value.content = istream.read_string ();
    int _len0 = istream.read_long ();
    value.answers = new String[_len0];
    for (int _o1 = 0;_o1 < value.answers.length; ++_o1)
      value.answers[_o1] = istream.read_string ();
    value.correctAnswer = istream.read_string ();
    value.timestamp = istream.read_longlong ();
    value.authorId = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StudySystem.Question value)
  {
    ostream.write_string (value.id);
    ostream.write_string (value.subject);
    ostream.write_string (value.content);
    ostream.write_long (value.answers.length);
    for (int _i0 = 0;_i0 < value.answers.length; ++_i0)
      ostream.write_string (value.answers[_i0]);
    ostream.write_string (value.correctAnswer);
    ostream.write_longlong (value.timestamp);
    ostream.write_string (value.authorId);
  }

}
