package StudySystem;


/**
* StudySystem/QuestionSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/


// TYPEDEFS (Fix for previous error)
public final class QuestionSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public StudySystem.Question value[] = null;

  public QuestionSequenceHolder ()
  {
  }

  public QuestionSequenceHolder (StudySystem.Question[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudySystem.QuestionSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudySystem.QuestionSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudySystem.QuestionSequenceHelper.type ();
  }

}
