package StudySystem;

/**
* StudySystem/ScoreEntryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class ScoreEntryHolder implements org.omg.CORBA.portable.Streamable
{
  public StudySystem.ScoreEntry value = null;

  public ScoreEntryHolder ()
  {
  }

  public ScoreEntryHolder (StudySystem.ScoreEntry initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudySystem.ScoreEntryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudySystem.ScoreEntryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudySystem.ScoreEntryHelper.type ();
  }

}
