package StudySystem;


/**
* StudySystem/ScoreEntry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class ScoreEntry implements org.omg.CORBA.portable.IDLEntity
{
  public String subject = null;
  public int score = (int)0;

  public ScoreEntry ()
  {
  } // ctor

  public ScoreEntry (String _subject, int _score)
  {
    subject = _subject;
    score = _score;
  } // ctor

} // class ScoreEntry
