package StudySystem;


/**
* StudySystem/ScoreEntryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

abstract public class ScoreEntryHelper
{
  private static String  _id = "IDL:StudySystem/ScoreEntry:1.0";

  public static void insert (org.omg.CORBA.Any a, StudySystem.ScoreEntry that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StudySystem.ScoreEntry extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "subject",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "score",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (StudySystem.ScoreEntryHelper.id (), "ScoreEntry", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StudySystem.ScoreEntry read (org.omg.CORBA.portable.InputStream istream)
  {
    StudySystem.ScoreEntry value = new StudySystem.ScoreEntry ();
    value.subject = istream.read_string ();
    value.score = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StudySystem.ScoreEntry value)
  {
    ostream.write_string (value.subject);
    ostream.write_long (value.score);
  }

}
