package StudySystem;


/**
* StudySystem/Statistics.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class Statistics implements org.omg.CORBA.portable.IDLEntity
{
  public String studentId = null;
  public StudySystem.ScoreEntry subjectScores[] = null;
  public long lastUpdate = (long)0;

  public Statistics ()
  {
  } // ctor

  public Statistics (String _studentId, StudySystem.ScoreEntry[] _subjectScores, long _lastUpdate)
  {
    studentId = _studentId;
    subjectScores = _subjectScores;
    lastUpdate = _lastUpdate;
  } // ctor

} // class Statistics
