package StudySystem;


/**
* StudySystem/StatisticsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

abstract public class StatisticsHelper
{
  private static String  _id = "IDL:StudySystem/Statistics:1.0";

  public static void insert (org.omg.CORBA.Any a, StudySystem.Statistics that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StudySystem.Statistics extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "studentId",
            _tcOf_members0,
            null);
          _tcOf_members0 = StudySystem.ScoreEntryHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "subjectScores",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[2] = new org.omg.CORBA.StructMember (
            "lastUpdate",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (StudySystem.StatisticsHelper.id (), "Statistics", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StudySystem.Statistics read (org.omg.CORBA.portable.InputStream istream)
  {
    StudySystem.Statistics value = new StudySystem.Statistics ();
    value.studentId = istream.read_string ();
    int _len0 = istream.read_long ();
    value.subjectScores = new StudySystem.ScoreEntry[_len0];
    for (int _o1 = 0;_o1 < value.subjectScores.length; ++_o1)
      value.subjectScores[_o1] = StudySystem.ScoreEntryHelper.read (istream);
    value.lastUpdate = istream.read_longlong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StudySystem.Statistics value)
  {
    ostream.write_string (value.studentId);
    ostream.write_long (value.subjectScores.length);
    for (int _i0 = 0;_i0 < value.subjectScores.length; ++_i0)
      StudySystem.ScoreEntryHelper.write (ostream, value.subjectScores[_i0]);
    ostream.write_longlong (value.lastUpdate);
  }

}
