package StudySystem;

/**
* StudySystem/StatisticsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Peer.idl
* Wednesday, December 3, 2025 10:44:05 PM WAT
*/

public final class StatisticsHolder implements org.omg.CORBA.portable.Streamable
{
  public StudySystem.Statistics value = null;

  public StatisticsHolder ()
  {
  }

  public StatisticsHolder (StudySystem.Statistics initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudySystem.StatisticsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudySystem.StatisticsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudySystem.StatisticsHelper.type ();
  }

}
